### ISSUE TITLE
add Together models to dashboard

### ISSUE THREAD

**Issue by InstincDev** [InstincDev/Together-Admin-Dash#2]
Add the schemas (found in the Together models folder) to the admin dash models folder

**Comment by InstincDev** [comment]
Add the schemas (found in the Together models folder) to the admin dash models folder

**Comment by DevRhyse** [comment]
For this, are you wanting to basically copy the whole folder? Or just the Events.js or User.js?
I'm assuming that the event's would be able to be seen after this point? (also assuming the .env is set up) Or would would there be something that needs to be edited as well in the other files?

**Comment by InstincDev** [comment]
After reviewing the event and user models in the Together schema, I think we should start by: 
- Updating the server.js
- Adding UserSchema
- Adding EventScema including the variables

The validation of the events can be addressed later.

**Comment by DevRhyse** [comment]
Ok sounds good. I can get started on this if you'd like.

**Comment by DevRhyse** [comment]
> After reviewing the event and user models in the Together schema, I think we should start by:
> 
> * Updating the server.js
> * Adding UserSchema
> * Adding EventScema including the variables
> 
> The validation of the events can be addressed later.

Ok sounds good. I can get started on this if you'd like.

**Comment by InstincDev** [comment]
I will assign this issue to you. You will need to pull from the development branch to gain access to the development database. If you have any questions feel free to ask.
