### ISSUE TITLE
create ReadMe

### ISSUE THREAD

**Issue by InstincDev** [InstincDev/Together-Admin-Dash#6]

**Comment by DevRhyse** [comment]
I would like to help out with this. 

Unsure what all you want stated inside of it. I'll copy a small portion of the Together Readme and tailor it to this. 
I'll be sure to add technologies used. Basic seup. 
Anything else I should be sure to add?

**Comment by InstincDev** [comment]
Using the Together readme as a template is a great start. Mainly include a project  description stating that this is an administrative dashboard for the Together project, and the technologies used to create it.
